Attempt fix build_docs.yml
Error:
```
Run sphinx-build doc _build

Application error!

Versions
========

* Platform:         linux; (Linux-6.8.0-1021-azure-x86_64-with-glibc2.39)
* Python version:   3.12.3 (CPython)
* Sphinx version:   8.2.3
* Docutils version: 0.21.2
* Jinja2 version:   3.1.2
* Pygments version: 2.17.2

Last Messages
=============

None.

Loaded Extensions
=================

None.

Traceback
=========

      File "/home/runner/.local/lib/python3.12/site-packages/sphinx/application.py", line 211, in __init__
        raise ApplicationError(
    sphinx.errors.ApplicationError: Cannot find source directory (/home/runner/work/flat-bug/flat-bug/doc)


The full traceback has been saved in:
/tmp/sphinx-err-vm7qu4an.log

To report this error to the developers, please open an issue at <https://github.com/sphinx-doc/sphinx/issues/>. Thanks!
Please also report this if it was a user error, so that a better error message can be provided next time.
Error: Process completed with exit code 2.
```